[package]
name = "l1p5"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "signal", "sync", "time"] }
flume = "0.11.0"
log = "0.4.22"